// @generated by scripts/convert-content.mjs
//
// Head sidecar for an @void/md island page whose byte-0 <script> block hides
// the frontmatter from Void core's title derivation. Regenerated by the
// converter; do not edit by hand. See renderHeadSidecar() for the full why.
import { defineHead } from 'void'

export const head = defineHead(() => ({
  title: 'NAPI-RS v2 发布',
}))
