// AUTO-GENERATED by scripts/build-nav.mjs — do not edit by hand.
// Re-run: node scripts/build-nav.mjs

export interface NavLeaf {
  title: string
  path: string
}

export interface NavGroup {
  group: string
  title: string
  items: NavLeaf[]
}

export interface NavTab {
  key: string
  title: string
  href?: string
}

export interface LocaleNav {
  tabs: NavTab[]
  /** Sidebar groups keyed by tab key ('docs' | 'blog' | 'changelog'). */
  sidebar: Record<string, NavGroup[]>
}

export type Locale = 'en' | 'cn' | 'pt-BR'

export const nav: Record<Locale, LocaleNav> = {
  en: {
    tabs: [
      {
        key: 'docs',
        title: 'Docs',
      },
      {
        key: 'blog',
        title: 'Blog',
      },
      {
        key: 'changelog',
        title: 'Changelog',
      },
    ],
    sidebar: {
      docs: [
        {
          group: 'introduction',
          title: 'Introduction',
          items: [
            {
              title: 'Getting started',
              path: 'docs/introduction/getting-started',
            },
            {
              title: 'A simple package',
              path: 'docs/introduction/simple-package',
            },
          ],
        },
        {
          group: 'concepts',
          title: 'Concepts',
          items: [
            {
              title: 'Exports',
              path: 'docs/concepts/exports',
            },
            {
              title: 'Module Initialization',
              path: 'docs/concepts/module-init',
            },
            {
              title: 'Naming conventions',
              path: 'docs/concepts/naming-conventions',
            },
            {
              title: 'Values',
              path: 'docs/concepts/values',
            },
            {
              title: 'Class',
              path: 'docs/concepts/class',
            },
            {
              title: 'Enum',
              path: 'docs/concepts/enum',
            },
            {
              title: 'Object',
              path: 'docs/concepts/object',
            },
            {
              title: 'Function',
              path: 'docs/concepts/function',
            },
            {
              title: 'ThreadsafeFunction',
              path: 'docs/concepts/threadsafe-function',
            },
            {
              title: 'AsyncTask',
              path: 'docs/concepts/async-task',
            },
            {
              title: 'Inject Env',
              path: 'docs/concepts/inject-env',
            },
            {
              title: 'Inject This',
              path: 'docs/concepts/inject-this',
            },
            {
              title: 'Reference',
              path: 'docs/concepts/reference',
            },
            {
              title: 'async fn',
              path: 'docs/concepts/async-fn',
            },
            {
              title: 'External',
              path: 'docs/concepts/external',
            },
            {
              title: 'Promise',
              path: 'docs/concepts/promise',
            },
            {
              title: 'Types Overwrite',
              path: 'docs/concepts/types-overwrite',
            },
            {
              title: 'Typed Array',
              path: 'docs/concepts/typed-array',
            },
            {
              title: 'Understanding Lifetime',
              path: 'docs/concepts/understanding-lifetime',
            },
            {
              title: 'Env',
              path: 'docs/concepts/env',
            },
            {
              title: 'WebAssembly',
              path: 'docs/concepts/webassembly',
            },
          ],
        },
        {
          group: 'cli',
          title: 'CLI',
          items: [
            {
              title: 'Programmatic API',
              path: 'docs/cli/programmatic-api',
            },
            {
              title: 'Build',
              path: 'docs/cli/build',
            },
            {
              title: 'Artifacts',
              path: 'docs/cli/artifacts',
            },
            {
              title: 'Prepublish',
              path: 'docs/cli/pre-publish',
            },
            {
              title: 'NAPI Config',
              path: 'docs/cli/napi-config',
            },
          ],
        },
        {
          group: 'deep-dive',
          title: 'Deep dive',
          items: [
            {
              title: 'Native module',
              path: 'docs/deep-dive/native-module',
            },
            {
              title: 'History',
              path: 'docs/deep-dive/history',
            },
            {
              title: 'Release native packages',
              path: 'docs/deep-dive/release',
            },
          ],
        },
        {
          group: 'cross-build',
          title: 'Cross build',
          items: [
            {
              title: 'Cross build',
              path: 'docs/cross-build',
            },
          ],
        },
        {
          group: 'more',
          title: 'More',
          items: [
            {
              title: 'Frequently Asked Questions',
              path: 'docs/more/faq',
            },
            {
              title: 'V2 to V3 Migration Guide',
              path: 'docs/more/v2-v3-migration-guide',
            },
          ],
        },
      ],
      blog: [
        {
          group: 'blog',
          title: 'Blog',
          items: [
            {
              title: 'Functions and Callbacks in NAPI-RS',
              path: 'blog/function-and-callbacks',
            },
            {
              title: 'Announce V3',
              path: 'blog/announce-v3',
            },
            {
              title: 'Announce V2',
              path: 'blog/announce-v2',
            },
          ],
        },
      ],
      changelog: [
        {
          group: 'changelog',
          title: 'Changelog',
          items: [
            {
              title: 'napi',
              path: 'changelog/napi',
            },
            {
              title: 'napi-derive',
              path: 'changelog/napi_derive',
            },
            {
              title: 'napi-sys',
              path: 'changelog/napi_sys',
            },
            {
              title: 'napi-build',
              path: 'changelog/napi_build',
            },
            {
              title: '@napi-rs/cli',
              path: 'changelog/napi-cli',
            },
          ],
        },
      ],
    },
  },
  cn: {
    tabs: [
      {
        key: 'docs',
        title: '文档',
      },
      {
        key: 'blog',
        title: '博客',
      },
      {
        key: 'changelog',
        title: '更新日志',
      },
    ],
    sidebar: {
      docs: [
        {
          group: 'introduction',
          title: '介绍',
          items: [
            {
              title: '起步',
              path: 'docs/introduction/getting-started',
            },
            {
              title: '编写发布一个简单的包',
              path: 'docs/introduction/simple-package',
            },
          ],
        },
        {
          group: 'concepts',
          title: '概念',
          items: [
            {
              title: '导出',
              path: 'docs/concepts/exports',
            },
            {
              title: '命名约定',
              path: 'docs/concepts/naming-conventions',
            },
            {
              title: '值',
              path: 'docs/concepts/values',
            },
            {
              title: '类',
              path: 'docs/concepts/class',
            },
            {
              title: '枚举',
              path: 'docs/concepts/enum',
            },
            {
              title: '对象',
              path: 'docs/concepts/object',
            },
            {
              title: '函数',
              path: 'docs/concepts/function',
            },
            {
              title: '线程安全函数',
              path: 'docs/concepts/threadsafe-function',
            },
            {
              title: '异步任务',
              path: 'docs/concepts/async-task',
            },
            {
              title: '注入Env',
              path: 'docs/concepts/inject-env',
            },
            {
              title: '注入This',
              path: 'docs/concepts/inject-this',
            },
            {
              title: '引用',
              path: 'docs/concepts/reference',
            },
            {
              title: '异步函数',
              path: 'docs/concepts/async-fn',
            },
            {
              title: 'External',
              path: 'docs/concepts/external',
            },
            {
              title: 'Await Promise',
              path: 'docs/concepts/await-promise',
            },
            {
              title: '重写类型',
              path: 'docs/concepts/types-overwrite',
            },
            {
              title: 'Typed Array',
              path: 'docs/concepts/typed-array',
            },
          ],
        },
        {
          group: 'cli',
          title: 'CLI',
          items: [
            {
              title: 'Build',
              path: 'docs/cli/build',
            },
            {
              title: 'Artifacts',
              path: 'docs/cli/artifacts',
            },
            {
              title: 'Prepublish',
              path: 'docs/cli/pre-publish',
            },
            {
              title: 'NAPI Config',
              path: 'docs/cli/napi-config',
            },
          ],
        },
        {
          group: 'deep-dive',
          title: 'Deep dive',
          items: [
            {
              title: 'Native module',
              path: 'docs/deep-dive/native-module',
            },
            {
              title: 'History',
              path: 'docs/deep-dive/history',
            },
            {
              title: 'Release native packages',
              path: 'docs/deep-dive/release',
            },
          ],
        },
        {
          group: 'cross-build',
          title: 'Cross build',
          items: [
            {
              title: 'Cross build',
              path: 'docs/cross-build',
            },
          ],
        },
        {
          group: 'ecosystem',
          title: 'Ecosystem',
          items: [
            {
              title: 'Ecosystem',
              path: 'docs/ecosystem',
            },
          ],
        },
        {
          group: 'more',
          title: 'More',
          items: [
            {
              title: 'Frequently Asked Questions',
              path: 'docs/more/faq',
            },
          ],
        },
      ],
      blog: [],
      changelog: [
        {
          group: 'changelog',
          title: 'Changelog',
          items: [
            {
              title: 'napi',
              path: 'changelog/napi',
            },
            {
              title: 'napi-derive',
              path: 'changelog/napi_derive',
            },
            {
              title: 'napi-sys',
              path: 'changelog/napi_sys',
            },
            {
              title: 'napi-build',
              path: 'changelog/napi_build',
            },
            {
              title: '@napi-rs/cli',
              path: 'changelog/napi-cli',
            },
          ],
        },
      ],
    },
  },
  'pt-BR': {
    tabs: [
      {
        key: 'docs',
        title: 'Documentação',
      },
      {
        key: 'blog',
        title: 'Blog',
      },
      {
        key: 'changelog',
        title: 'Changelog',
      },
    ],
    sidebar: {
      docs: [
        {
          group: 'introduction',
          title: 'Introdução',
          items: [
            {
              title: 'Começando',
              path: 'docs/introduction/getting-started',
            },
            {
              title: 'Um pacote simples',
              path: 'docs/introduction/simple-package',
            },
          ],
        },
        {
          group: 'concepts',
          title: 'Conceitos',
          items: [
            {
              title: 'Exports',
              path: 'docs/concepts/exports',
            },
            {
              title: 'Naming conventions',
              path: 'docs/concepts/naming-conventions',
            },
            {
              title: 'Values',
              path: 'docs/concepts/values',
            },
            {
              title: 'Class',
              path: 'docs/concepts/class',
            },
            {
              title: 'Enum',
              path: 'docs/concepts/enum',
            },
            {
              title: 'Object',
              path: 'docs/concepts/object',
            },
            {
              title: 'Function',
              path: 'docs/concepts/function',
            },
            {
              title: 'ThreadsafeFunction',
              path: 'docs/concepts/threadsafe-function',
            },
            {
              title: 'AsyncTask',
              path: 'docs/concepts/async-task',
            },
            {
              title: 'Inject Env',
              path: 'docs/concepts/inject-env',
            },
            {
              title: 'Inject This',
              path: 'docs/concepts/inject-this',
            },
            {
              title: 'Reference',
              path: 'docs/concepts/reference',
            },
            {
              title: 'async fn',
              path: 'docs/concepts/async-fn',
            },
            {
              title: 'External',
              path: 'docs/concepts/external',
            },
            {
              title: 'Await Promise',
              path: 'docs/concepts/await-promise',
            },
            {
              title: 'Sobrescrita de Tipos',
              path: 'docs/concepts/types-overwrite',
            },
            {
              title: 'Typed Array',
              path: 'docs/concepts/typed-array',
            },
          ],
        },
        {
          group: 'cli',
          title: 'CLI',
          items: [
            {
              title: 'Build',
              path: 'docs/cli/build',
            },
            {
              title: 'Artifacts',
              path: 'docs/cli/artifacts',
            },
            {
              title: 'Prepublish',
              path: 'docs/cli/pre-publish',
            },
            {
              title: 'NAPI Config',
              path: 'docs/cli/napi-config',
            },
          ],
        },
        {
          group: 'deep-dive',
          title: 'Aprofundamento',
          items: [
            {
              title: 'Módulo nativo',
              path: 'docs/deep-dive/native-module',
            },
            {
              title: 'História',
              path: 'docs/deep-dive/history',
            },
            {
              title: 'Release de pacotes nativos',
              path: 'docs/deep-dive/release',
            },
          ],
        },
        {
          group: 'cross-build',
          title: 'Compilação cruzada',
          items: [
            {
              title: 'Compilação cruzada',
              path: 'docs/cross-build',
            },
          ],
        },
        {
          group: 'ecosystem',
          title: 'Ecossistema',
          items: [
            {
              title: 'Ecossistema',
              path: 'docs/ecosystem',
            },
          ],
        },
        {
          group: 'more',
          title: 'Mais',
          items: [
            {
              title: 'Perguntas Frequentes',
              path: 'docs/more/faq',
            },
          ],
        },
      ],
      blog: [],
      changelog: [],
    },
  },
} as const

export const locales: { locale: Locale; text: string }[] = [
  {
    locale: 'en',
    text: 'English',
  },
  {
    locale: 'cn',
    text: '简体中文',
  },
  {
    locale: 'pt-BR',
    text: 'Português do Brasil',
  },
] as const
