// AUTO-GENERATED by scripts/build-nav.mjs — do not edit by hand.
// Re-run: node scripts/build-nav.mjs

export interface NavLeaf {
  title: string
  path: string
}

export interface NavGroup {
  group: string
  /**
   * Display label for the group header. A BLANK title ('') marks a "flat" group:
   * its leaves are rendered directly (no collapsible sidebar header, no group
   * breadcrumb crumb), matching live napi.rs for blog/changelog whose source
   * _meta is a flat slug->title map. Docs groups always carry a real title.
   */
  title: string
  items: NavLeaf[]
}

export interface NavTab {
  key: string
  title: string
  href?: string
}

export interface LocaleNav {
  tabs: NavTab[]
  /** Sidebar groups keyed by tab key ('docs' | 'blog' | 'changelog'). */
  sidebar: Record<string, NavGroup[]>
}

export type Locale = 'en' | 'cn' | 'pt-BR'

export const nav: Record<Locale, LocaleNav> = {
  en: {
    tabs: [
      {
        key: 'docs',
        title: 'Docs',
      },
      {
        key: 'blog',
        title: 'Blog',
      },
      {
        key: 'changelog',
        title: 'Changelog',
      },
    ],
    sidebar: {
      docs: [
        {
          group: 'introduction',
          title: 'Introduction',
          items: [
            {
              title: 'Getting started',
              path: 'docs/introduction/getting-started',
            },
            {
              title: 'Build your first package',
              path: 'docs/introduction/simple-package',
            },
            {
              title: 'Manual setup',
              path: 'docs/introduction/manual-setup',
            },
          ],
        },
        {
          group: 'concepts',
          title: 'Concepts & reference',
          items: [
            {
              title: 'Exports',
              path: 'docs/concepts/exports',
            },
            {
              title: 'Module Initialization',
              path: 'docs/concepts/module-init',
            },
            {
              title: 'Naming conventions',
              path: 'docs/concepts/naming-conventions',
            },
            {
              title: '#[napi] attributes',
              path: 'docs/concepts/napi-attributes',
            },
            {
              title: 'Values',
              path: 'docs/concepts/values',
            },
            {
              title: 'Type conversions',
              path: 'docs/concepts/type-conversions',
            },
            {
              title: 'Class',
              path: 'docs/concepts/class',
            },
            {
              title: 'Enum',
              path: 'docs/concepts/enum',
            },
            {
              title: 'Object',
              path: 'docs/concepts/object',
            },
            {
              title: 'Function',
              path: 'docs/concepts/function',
            },
            {
              title: 'Errors and panics',
              path: 'docs/concepts/error-handling',
            },
            {
              title: 'ThreadsafeFunction',
              path: 'docs/concepts/threadsafe-function',
            },
            {
              title: 'AsyncTask',
              path: 'docs/concepts/async-task',
            },
            {
              title: 'Inject Env',
              path: 'docs/concepts/inject-env',
            },
            {
              title: 'Inject This',
              path: 'docs/concepts/inject-this',
            },
            {
              title: 'Reference',
              path: 'docs/concepts/reference',
            },
            {
              title: 'async fn',
              path: 'docs/concepts/async-fn',
            },
            {
              title: 'External',
              path: 'docs/concepts/external',
            },
            {
              title: 'Promise',
              path: 'docs/concepts/promise',
            },
            {
              title: 'Iterators',
              path: 'docs/concepts/iterators',
            },
            {
              title: 'Types Overwrite',
              path: 'docs/concepts/types-overwrite',
            },
            {
              title: 'Typed Array',
              path: 'docs/concepts/typed-array',
            },
            {
              title: 'Understanding Lifetime',
              path: 'docs/concepts/understanding-lifetime',
            },
            {
              title: 'Env',
              path: 'docs/concepts/env',
            },
            {
              title: 'Cargo features',
              path: 'docs/concepts/cargo-features',
            },
            {
              title: 'WebAssembly',
              path: 'docs/concepts/webassembly',
            },
          ],
        },
        {
          group: 'cli',
          title: 'CLI',
          items: [
            {
              title: 'New project',
              path: 'docs/cli/new',
            },
            {
              title: 'Rename project',
              path: 'docs/cli/rename',
            },
            {
              title: 'Build',
              path: 'docs/cli/build',
            },
            {
              title: 'NAPI Config',
              path: 'docs/cli/napi-config',
            },
            {
              title: 'Programmatic API',
              path: 'docs/cli/programmatic-api',
            },
            {
              title: 'Create npm directories',
              path: 'docs/cli/create-npm-dirs',
            },
            {
              title: 'Artifacts',
              path: 'docs/cli/artifacts',
            },
            {
              title: 'Universalize',
              path: 'docs/cli/universalize',
            },
            {
              title: 'Version packages',
              path: 'docs/cli/version',
            },
            {
              title: 'Prepublish',
              path: 'docs/cli/pre-publish',
            },
          ],
        },
        {
          group: 'deep-dive',
          title: 'Deep dive',
          items: [
            {
              title: 'Native module',
              path: 'docs/deep-dive/native-module',
            },
            {
              title: 'History',
              path: 'docs/deep-dive/history',
            },
            {
              title: 'Release native packages',
              path: 'docs/deep-dive/release',
            },
          ],
        },
        {
          group: 'cross-build',
          title: 'Cross build',
          items: [
            {
              title: 'Cross build',
              path: 'docs/cross-build',
            },
          ],
        },
        {
          group: 'more',
          title: 'Guides & help',
          items: [
            {
              title: 'Support and compatibility',
              path: 'docs/more/support-compatibility',
            },
            {
              title: 'Support matrix badge',
              path: 'docs/more/support-matrix-badge',
            },
            {
              title: 'Testing and debugging',
              path: 'docs/more/testing-debugging',
            },
            {
              title: 'Async and concurrency guide',
              path: 'docs/more/async-concurrency',
            },
            {
              title: 'Bundlers and frameworks',
              path: 'docs/more/integrations',
            },
            {
              title: 'Troubleshooting',
              path: 'docs/more/troubleshooting',
            },
            {
              title: 'Cross-build FAQ',
              path: 'docs/more/faq',
            },
            {
              title: 'V2 to V3 Migration Guide',
              path: 'docs/more/v2-v3-migration-guide',
            },
          ],
        },
      ],
      blog: [
        {
          group: 'blog',
          title: '',
          items: [
            {
              title: 'Functions and Callbacks in NAPI-RS',
              path: 'blog/function-and-callbacks',
            },
            {
              title: 'Announce V3',
              path: 'blog/announce-v3',
            },
            {
              title: 'Announce V2',
              path: 'blog/announce-v2',
            },
          ],
        },
      ],
      changelog: [
        {
          group: 'changelog',
          title: '',
          items: [
            {
              title: 'napi',
              path: 'changelog/napi',
            },
            {
              title: 'napi-derive',
              path: 'changelog/napi_derive',
            },
            {
              title: 'napi-sys',
              path: 'changelog/napi_sys',
            },
            {
              title: 'napi-build',
              path: 'changelog/napi_build',
            },
            {
              title: '@napi-rs/cli',
              path: 'changelog/napi-cli',
            },
          ],
        },
      ],
    },
  },
  cn: {
    tabs: [
      {
        key: 'docs',
        title: '文档',
      },
      {
        key: 'blog',
        title: '博客',
      },
      {
        key: 'changelog',
        title: '更新日志',
      },
    ],
    sidebar: {
      docs: [
        {
          group: 'introduction',
          title: '介绍',
          items: [
            {
              title: '快速开始',
              path: 'docs/introduction/getting-started',
            },
            {
              title: '构建你的第一个包',
              path: 'docs/introduction/simple-package',
            },
            {
              title: '手动配置',
              path: 'docs/introduction/manual-setup',
            },
          ],
        },
        {
          group: 'concepts',
          title: '概念与参考',
          items: [
            {
              title: '导出',
              path: 'docs/concepts/exports',
            },
            {
              title: '模块初始化',
              path: 'docs/concepts/module-init',
            },
            {
              title: '命名约定',
              path: 'docs/concepts/naming-conventions',
            },
            {
              title: '#[napi] 属性',
              path: 'docs/concepts/napi-attributes',
            },
            {
              title: '值',
              path: 'docs/concepts/values',
            },
            {
              title: '类型转换',
              path: 'docs/concepts/type-conversions',
            },
            {
              title: '类',
              path: 'docs/concepts/class',
            },
            {
              title: '枚举',
              path: 'docs/concepts/enum',
            },
            {
              title: '对象',
              path: 'docs/concepts/object',
            },
            {
              title: '函数',
              path: 'docs/concepts/function',
            },
            {
              title: '错误与 panic',
              path: 'docs/concepts/error-handling',
            },
            {
              title: '线程安全函数',
              path: 'docs/concepts/threadsafe-function',
            },
            {
              title: '异步任务',
              path: 'docs/concepts/async-task',
            },
            {
              title: '注入 Env',
              path: 'docs/concepts/inject-env',
            },
            {
              title: '注入 This',
              path: 'docs/concepts/inject-this',
            },
            {
              title: '引用',
              path: 'docs/concepts/reference',
            },
            {
              title: '异步函数',
              path: 'docs/concepts/async-fn',
            },
            {
              title: '外部数据',
              path: 'docs/concepts/external',
            },
            {
              title: 'Promise',
              path: 'docs/concepts/promise',
            },
            {
              title: '迭代器',
              path: 'docs/concepts/iterators',
            },
            {
              title: '重写类型',
              path: 'docs/concepts/types-overwrite',
            },
            {
              title: '类型化数组',
              path: 'docs/concepts/typed-array',
            },
            {
              title: '理解生命周期',
              path: 'docs/concepts/understanding-lifetime',
            },
            {
              title: 'Env',
              path: 'docs/concepts/env',
            },
            {
              title: 'Cargo 特性',
              path: 'docs/concepts/cargo-features',
            },
            {
              title: 'WebAssembly',
              path: 'docs/concepts/webassembly',
            },
          ],
        },
        {
          group: 'cli',
          title: 'CLI',
          items: [
            {
              title: '新建项目',
              path: 'docs/cli/new',
            },
            {
              title: '重命名项目',
              path: 'docs/cli/rename',
            },
            {
              title: '构建',
              path: 'docs/cli/build',
            },
            {
              title: 'NAPI 配置',
              path: 'docs/cli/napi-config',
            },
            {
              title: '编程式 API',
              path: 'docs/cli/programmatic-api',
            },
            {
              title: '创建 npm 目录',
              path: 'docs/cli/create-npm-dirs',
            },
            {
              title: '收集构建产物',
              path: 'docs/cli/artifacts',
            },
            {
              title: '合并通用二进制',
              path: 'docs/cli/universalize',
            },
            {
              title: '更新包版本',
              path: 'docs/cli/version',
            },
            {
              title: '发布前处理',
              path: 'docs/cli/pre-publish',
            },
          ],
        },
        {
          group: 'deep-dive',
          title: '深入理解',
          items: [
            {
              title: '原生模块',
              path: 'docs/deep-dive/native-module',
            },
            {
              title: '历史',
              path: 'docs/deep-dive/history',
            },
            {
              title: '发布原生包',
              path: 'docs/deep-dive/release',
            },
          ],
        },
        {
          group: 'cross-build',
          title: '交叉编译',
          items: [
            {
              title: '交叉编译',
              path: 'docs/cross-build',
            },
          ],
        },
        {
          group: 'more',
          title: '指南与帮助',
          items: [
            {
              title: '支持与兼容性',
              path: 'docs/more/support-compatibility',
            },
            {
              title: '支持矩阵徽章',
              path: 'docs/more/support-matrix-badge',
            },
            {
              title: '测试与调试',
              path: 'docs/more/testing-debugging',
            },
            {
              title: '异步与并发指南',
              path: 'docs/more/async-concurrency',
            },
            {
              title: '打包工具与框架',
              path: 'docs/more/integrations',
            },
            {
              title: '故障排查',
              path: 'docs/more/troubleshooting',
            },
            {
              title: '交叉编译常见问题',
              path: 'docs/more/faq',
            },
            {
              title: 'V2 到 V3 迁移指南',
              path: 'docs/more/v2-v3-migration-guide',
            },
          ],
        },
      ],
      blog: [
        {
          group: 'blog',
          title: '',
          items: [
            {
              title: 'Functions and Callbacks in NAPI-RS',
              path: 'blog/function-and-callbacks',
            },
            {
              title: 'Announce V3',
              path: 'blog/announce-v3',
            },
            {
              title: 'NAPI-RS v2 发布',
              path: 'blog/announce-v2',
            },
          ],
        },
      ],
      changelog: [
        {
          group: 'changelog',
          title: '',
          items: [
            {
              title: 'napi',
              path: 'changelog/napi',
            },
            {
              title: 'napi-derive',
              path: 'changelog/napi_derive',
            },
            {
              title: 'napi-sys',
              path: 'changelog/napi_sys',
            },
            {
              title: 'napi-build',
              path: 'changelog/napi_build',
            },
            {
              title: '@napi-rs/cli',
              path: 'changelog/napi-cli',
            },
          ],
        },
      ],
    },
  },
  'pt-BR': {
    tabs: [
      {
        key: 'docs',
        title: 'Documentação',
      },
      {
        key: 'blog',
        title: 'Blog',
      },
      {
        key: 'changelog',
        title: 'Changelog',
      },
    ],
    sidebar: {
      docs: [
        {
          group: 'introduction',
          title: 'Introdução',
          items: [
            {
              title: 'Primeiros passos',
              path: 'docs/introduction/getting-started',
            },
            {
              title: 'Crie seu primeiro pacote',
              path: 'docs/introduction/simple-package',
            },
            {
              title: 'Configuração manual',
              path: 'docs/introduction/manual-setup',
            },
          ],
        },
        {
          group: 'concepts',
          title: 'Conceitos e referência',
          items: [
            {
              title: 'Exportações',
              path: 'docs/concepts/exports',
            },
            {
              title: 'Inicialização do módulo',
              path: 'docs/concepts/module-init',
            },
            {
              title: 'Convenções de nomenclatura',
              path: 'docs/concepts/naming-conventions',
            },
            {
              title: 'Atributos #[napi]',
              path: 'docs/concepts/napi-attributes',
            },
            {
              title: 'Valores',
              path: 'docs/concepts/values',
            },
            {
              title: 'Conversões de tipos',
              path: 'docs/concepts/type-conversions',
            },
            {
              title: 'Classes',
              path: 'docs/concepts/class',
            },
            {
              title: 'Enums',
              path: 'docs/concepts/enum',
            },
            {
              title: 'Objetos',
              path: 'docs/concepts/object',
            },
            {
              title: 'Funções',
              path: 'docs/concepts/function',
            },
            {
              title: 'Erros e panics',
              path: 'docs/concepts/error-handling',
            },
            {
              title: 'ThreadsafeFunction',
              path: 'docs/concepts/threadsafe-function',
            },
            {
              title: 'AsyncTask',
              path: 'docs/concepts/async-task',
            },
            {
              title: 'Injetar Env',
              path: 'docs/concepts/inject-env',
            },
            {
              title: 'Injetar This',
              path: 'docs/concepts/inject-this',
            },
            {
              title: 'Referências',
              path: 'docs/concepts/reference',
            },
            {
              title: 'async fn',
              path: 'docs/concepts/async-fn',
            },
            {
              title: 'External',
              path: 'docs/concepts/external',
            },
            {
              title: 'Promise',
              path: 'docs/concepts/promise',
            },
            {
              title: 'Iteradores',
              path: 'docs/concepts/iterators',
            },
            {
              title: 'Sobrescrita de Tipos',
              path: 'docs/concepts/types-overwrite',
            },
            {
              title: 'Typed Array',
              path: 'docs/concepts/typed-array',
            },
            {
              title: 'Entendendo lifetimes',
              path: 'docs/concepts/understanding-lifetime',
            },
            {
              title: 'Env',
              path: 'docs/concepts/env',
            },
            {
              title: 'Features do Cargo',
              path: 'docs/concepts/cargo-features',
            },
            {
              title: 'WebAssembly',
              path: 'docs/concepts/webassembly',
            },
          ],
        },
        {
          group: 'cli',
          title: 'CLI',
          items: [
            {
              title: 'Novo projeto',
              path: 'docs/cli/new',
            },
            {
              title: 'Renomear projeto',
              path: 'docs/cli/rename',
            },
            {
              title: 'Compilação',
              path: 'docs/cli/build',
            },
            {
              title: 'Configuração NAPI',
              path: 'docs/cli/napi-config',
            },
            {
              title: 'API programática',
              path: 'docs/cli/programmatic-api',
            },
            {
              title: 'Criar diretórios npm',
              path: 'docs/cli/create-npm-dirs',
            },
            {
              title: 'Coletar artefatos',
              path: 'docs/cli/artifacts',
            },
            {
              title: 'Universalizar',
              path: 'docs/cli/universalize',
            },
            {
              title: 'Versionar pacotes',
              path: 'docs/cli/version',
            },
            {
              title: 'Pré-publicação',
              path: 'docs/cli/pre-publish',
            },
          ],
        },
        {
          group: 'deep-dive',
          title: 'Aprofundamento',
          items: [
            {
              title: 'Módulo nativo',
              path: 'docs/deep-dive/native-module',
            },
            {
              title: 'História',
              path: 'docs/deep-dive/history',
            },
            {
              title: 'Publicação de pacotes nativos',
              path: 'docs/deep-dive/release',
            },
          ],
        },
        {
          group: 'cross-build',
          title: 'Compilação cruzada',
          items: [
            {
              title: 'Compilação cruzada',
              path: 'docs/cross-build',
            },
          ],
        },
        {
          group: 'more',
          title: 'Guias e ajuda',
          items: [
            {
              title: 'Suporte e compatibilidade',
              path: 'docs/more/support-compatibility',
            },
            {
              title: 'Badge da matriz de suporte',
              path: 'docs/more/support-matrix-badge',
            },
            {
              title: 'Testes e depuração',
              path: 'docs/more/testing-debugging',
            },
            {
              title: 'Guia de async e concorrência',
              path: 'docs/more/async-concurrency',
            },
            {
              title: 'Bundlers e frameworks',
              path: 'docs/more/integrations',
            },
            {
              title: 'Solução de problemas',
              path: 'docs/more/troubleshooting',
            },
            {
              title: 'FAQ de compilação cruzada',
              path: 'docs/more/faq',
            },
            {
              title: 'Guia de migração da V2 para a V3',
              path: 'docs/more/v2-v3-migration-guide',
            },
          ],
        },
      ],
      blog: [
        {
          group: 'blog',
          title: '',
          items: [
            {
              title: 'Functions and Callbacks in NAPI-RS',
              path: 'blog/function-and-callbacks',
            },
            {
              title: 'Announce V3',
              path: 'blog/announce-v3',
            },
            {
              title: 'Announce V2',
              path: 'blog/announce-v2',
            },
          ],
        },
      ],
      changelog: [
        {
          group: 'changelog',
          title: '',
          items: [
            {
              title: 'napi',
              path: 'changelog/napi',
            },
            {
              title: 'napi-derive',
              path: 'changelog/napi_derive',
            },
            {
              title: 'napi-sys',
              path: 'changelog/napi_sys',
            },
            {
              title: 'napi-build',
              path: 'changelog/napi_build',
            },
            {
              title: '@napi-rs/cli',
              path: 'changelog/napi-cli',
            },
          ],
        },
      ],
    },
  },
} as const

export const locales: { locale: Locale; text: string }[] = [
  {
    locale: 'en',
    text: 'English',
  },
  {
    locale: 'cn',
    text: '简体中文',
  },
  {
    locale: 'pt-BR',
    text: 'Português do Brasil',
  },
] as const
