// scripts/build-nav.mjs
// Reads legacy_pages/**/_meta.<locale>.json and generates lib/nav/index.ts
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { execSync } from 'node:child_process'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const legacyPages = join(root, 'legacy_pages')
const outFile = join(root, 'lib', 'nav', 'index.ts')

const LOCALES = ['en', 'cn', 'pt-BR']
const LOCALE_LABELS = {
  en: 'English',
  cn: '简体中文',
  'pt-BR': 'Português do Brasil',
}

function readMeta(dir, locale) {
  const file = join(dir, `_meta.${locale}.json`)
  if (!existsSync(file)) return null
  return JSON.parse(readFileSync(file, 'utf8'))
}

/** Returns true if a content file (.mdx or .md) exists for the given route path and locale.
 *  routePath is relative to legacy_pages, e.g. "docs/cross-build" or "docs/concepts/class".
 */
function contentExists(routePath, locale) {
  const base = join(legacyPages, routePath)
  return (
    existsSync(`${base}.${locale}.mdx`) || existsSync(`${base}.${locale}.md`)
  )
}

// Build docs sidebar groups for a locale
function buildDocsSidebar(locale) {
  const docsMeta = readMeta(join(legacyPages, 'docs'), locale)
  if (!docsMeta) return []

  const groups = []
  for (const [key, value] of Object.entries(docsMeta)) {
    // Skip display:hidden entries
    if (typeof value === 'object' && value.display === 'hidden') continue
    const title = typeof value === 'string' ? value : value.title
    const subDir = join(legacyPages, 'docs', key)
    const subMeta = readMeta(subDir, locale)

    if (subMeta) {
      // It's a group with sub-items — filter to only items with content files
      const items = []
      for (const [slug, v] of Object.entries(subMeta)) {
        // Skip display:hidden entries in sub-sections
        if (typeof v === 'object' && v.display === 'hidden') continue
        if (!contentExists(`docs/${key}/${slug}`, locale)) continue
        items.push({
          title: typeof v === 'string' ? v : v.title,
          path: `docs/${key}/${slug}`,
        })
      }
      // Omit the group entirely if it has no items for this locale
      if (items.length > 0) {
        groups.push({ group: key, title, items })
      }
    } else {
      // It's a direct leaf page — only include if the content file exists
      if (!contentExists(`docs/${key}`, locale)) continue
      groups.push({
        group: key,
        title,
        items: [{ title, path: `docs/${key}` }],
      })
    }
  }
  return groups
}

function buildBlogSidebar(locale) {
  const meta = readMeta(join(legacyPages, 'blog'), locale)
  if (!meta) return []
  const items = []
  for (const [slug, v] of Object.entries(meta)) {
    if (typeof v === 'object' && v.display === 'hidden') continue
    if (!contentExists(`blog/${slug}`, locale)) continue
    items.push({
      title: typeof v === 'string' ? v : v.title,
      path: `blog/${slug}`,
    })
  }
  if (items.length === 0) return []
  // Blog is a FLAT list (the source _meta is a direct slug->title map, with no
  // intermediate group). Emit ONE group with a blank title — the "flat group"
  // marker the Sidebar/Breadcrumb honor to skip the redundant section-named
  // header + crumb (matching live napi.rs). Docs, by contrast, has real groups.
  return [{ group: 'blog', title: '', items }]
}

function buildChangelogSidebar(locale) {
  const meta = readMeta(join(legacyPages, 'changelog'), locale)
  if (!meta) return []
  const items = []
  for (const [slug, v] of Object.entries(meta)) {
    if (typeof v === 'object' && v.display === 'hidden') continue
    if (!contentExists(`changelog/${slug}`, locale)) continue
    items.push({
      title: typeof v === 'string' ? v : v.title,
      path: `changelog/${slug}`,
    })
  }
  if (items.length === 0) return []
  // Changelog is a FLAT list (source _meta is a direct slug->title map). Same
  // "flat group" marker as blog: a blank title means render the leaves directly
  // with no group header/crumb, unlike the real multi-group docs sidebar.
  return [{ group: 'changelog', title: '', items }]
}

function buildLocaleNav(locale) {
  const topMeta = readMeta(legacyPages, locale)

  // Tabs: type:page entries only (exclude display:hidden and raw layout)
  const tabs = []
  for (const [key, value] of Object.entries(topMeta)) {
    if (typeof value === 'object' && value.type === 'page') {
      tabs.push({ key, title: value.title })
    }
  }

  const sidebar = {
    docs: buildDocsSidebar(locale),
    blog: buildBlogSidebar(locale),
    changelog: buildChangelogSidebar(locale),
  }

  return { tabs, sidebar }
}

const nav = {}
for (const locale of LOCALES) {
  nav[locale] = buildLocaleNav(locale)
}

const locales = LOCALES.map((l) => ({ locale: l, text: LOCALE_LABELS[l] }))

// Generate TypeScript output
const ts = `// AUTO-GENERATED by scripts/build-nav.mjs — do not edit by hand.
// Re-run: node scripts/build-nav.mjs

export interface NavLeaf {
  title: string
  path: string
}

export interface NavGroup {
  group: string
  /**
   * Display label for the group header. A BLANK title ('') marks a "flat" group:
   * its leaves are rendered directly (no collapsible sidebar header, no group
   * breadcrumb crumb), matching live napi.rs for blog/changelog whose source
   * _meta is a flat slug->title map. Docs groups always carry a real title.
   */
  title: string
  items: NavLeaf[]
}

export interface NavTab {
  key: string
  title: string
  href?: string
}

export interface LocaleNav {
  tabs: NavTab[]
  /** Sidebar groups keyed by tab key ('docs' | 'blog' | 'changelog'). */
  sidebar: Record<string, NavGroup[]>
}

export type Locale = 'en' | 'cn' | 'pt-BR'

export const nav: Record<Locale, LocaleNav> = ${JSON.stringify(nav, null, 2)} as const

export const locales: { locale: Locale; text: string }[] = ${JSON.stringify(locales, null, 2)} as const
`

writeFileSync(outFile, ts, 'utf8')
// Auto-format so the committed file matches what `vp fmt` would produce (uses oxfmt).
try {
  execSync(`vp fmt "${outFile}" --write`, { cwd: root, stdio: 'pipe' })
} catch {
  // vp not on PATH; file will be formatted by pre-commit hook
}
console.log(`Written ${outFile}`)
