// scripts/build-nav.mjs
// Reads legacy_pages/**/_meta.<locale>.json and generates lib/nav/index.ts
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')
const legacyPages = join(root, 'legacy_pages')
const outFile = join(root, 'lib', 'nav', 'index.ts')

const LOCALES = ['en', 'cn', 'pt-BR']
const LOCALE_LABELS = {
  en: 'English',
  cn: '简体中文',
  'pt-BR': 'Português do Brasil',
}

function readMeta(dir, locale) {
  const file = join(dir, `_meta.${locale}.json`)
  if (!existsSync(file)) return null
  return JSON.parse(readFileSync(file, 'utf8'))
}

function buildLeaf(group, slug, title) {
  return { title, path: group ? `${group}/${slug}` : slug }
}

// Build docs sidebar groups for a locale
function buildDocsSidebar(locale) {
  const docsMeta = readMeta(join(legacyPages, 'docs'), locale)
  if (!docsMeta) return []

  const groups = []
  for (const [key, value] of Object.entries(docsMeta)) {
    const title = typeof value === 'string' ? value : value.title
    const subDir = join(legacyPages, 'docs', key)
    const subMeta = readMeta(subDir, locale)

    if (subMeta) {
      // It's a group with sub-items
      const items = Object.entries(subMeta).map(([slug, v]) => ({
        title: typeof v === 'string' ? v : v.title,
        path: `docs/${key}/${slug}`,
      }))
      groups.push({ group: key, title, items })
    } else {
      // It's a direct leaf page - treat as a single-item group OR add to a "flat" group
      // Use group key = key, with single item whose path = `docs/${key}`
      groups.push({
        group: key,
        title,
        items: [{ title, path: `docs/${key}` }],
      })
    }
  }
  return groups
}

function buildBlogSidebar(locale) {
  const meta = readMeta(join(legacyPages, 'blog'), locale)
  if (!meta) return []
  const items = Object.entries(meta).map(([slug, v]) => ({
    title: typeof v === 'string' ? v : v.title,
    path: `blog/${slug}`,
  }))
  return [{ group: 'blog', title: 'Blog', items }]
}

function buildChangelogSidebar(locale) {
  const meta = readMeta(join(legacyPages, 'changelog'), locale)
  if (!meta) return []
  const items = Object.entries(meta).map(([slug, v]) => ({
    title: typeof v === 'string' ? v : v.title,
    path: `changelog/${slug}`,
  }))
  return [{ group: 'changelog', title: 'Changelog', items }]
}

function buildLocaleNav(locale) {
  const topMeta = readMeta(legacyPages, locale)

  // Tabs: type:page entries only (exclude display:hidden and raw layout)
  const tabs = []
  for (const [key, value] of Object.entries(topMeta)) {
    if (typeof value === 'object' && value.type === 'page') {
      tabs.push({ key, title: value.title })
    }
  }

  const sidebar = {
    docs: buildDocsSidebar(locale),
    blog: buildBlogSidebar(locale),
    changelog: buildChangelogSidebar(locale),
  }

  return { tabs, sidebar }
}

const nav = {}
for (const locale of LOCALES) {
  nav[locale] = buildLocaleNav(locale)
}

const locales = LOCALES.map((l) => ({ locale: l, text: LOCALE_LABELS[l] }))

// Generate TypeScript output
const ts = `// AUTO-GENERATED by scripts/build-nav.mjs — do not edit by hand.
// Re-run: node scripts/build-nav.mjs

export interface NavLeaf {
  title: string
  path: string
}

export interface NavGroup {
  group: string
  title: string
  items: NavLeaf[]
}

export interface NavTab {
  key: string
  title: string
  href?: string
}

export interface LocaleNav {
  tabs: NavTab[]
  /** Sidebar groups keyed by tab key ('docs' | 'blog' | 'changelog'). */
  sidebar: Record<string, NavGroup[]>
}

export type Locale = 'en' | 'cn' | 'pt-BR'

export const nav: Record<Locale, LocaleNav> = ${JSON.stringify(nav, null, 2)} as const

export const locales: { locale: Locale; text: string }[] = ${JSON.stringify(locales, null, 2)} as const
`

writeFileSync(outFile, ts, 'utf8')
console.log(`Written ${outFile}`)
