// scripts/build-changelog.ts
//
// Fetches the FULL napi-rs/napi-rs release history once and renders the
// per-package changelog HTML, writing it to a committed build artifact:
// lib/changelog/changelog-data.gen.ts (keyed by package slug).
//
// Why a committed build artifact (mirrors scripts/fetch-link-previews.mjs):
// rendering the full history (~700 releases × Shiki) is far too heavy to do per
// request — on Cloudflare it OOMs a worker isolate (128 MB) and returns a raw
// 1101. Baking it here means the changelog pages carry NO runtime loader, so
// Void auto-prerenders them to pure-static, cookie-agnostic HTML (the same
// profile as the .md docs pages) and deploys stay network-free. Re-run this
// only when new releases should be published; the output is committed.
//
// Run: GITHUB_TOKEN=… oxnode scripts/build-changelog.ts
//   (the token is OPT-IN — anonymous works but is rate-limited; CI sets it.)
//
// Throws (exit 1) on any GitHub / render failure so a transient outage can
// never overwrite the last-good committed data with a broken/partial file.

import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  buildChangelogMarkdown,
  renderChangelogHtml,
} from '../lib/changelog/render.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')
const outFile = join(root, 'lib', 'changelog', 'changelog-data.gen.ts')

const RELEASES_URL =
  'https://api.github.com/repos/napi-rs/napi-rs/releases?per_page=100'

// Page slug -> the legacy getStaticProps('<filter>') string. The filter is what
// `name.startsWith(...)` matches; `napi` deliberately also catches napi-derive/
// sys/build (a faithfully-replicated legacy quirk). Keys match the slug each
// page island imports from changelog-data.gen.ts.
const PACKAGES: ReadonlyArray<{ slug: string; filter: string }> = [
  { slug: 'napi', filter: 'napi' },
  { slug: 'napi-build', filter: 'napi-build' },
  { slug: 'napi-derive', filter: 'napi-derive' },
  { slug: 'napi-sys', filter: 'napi-sys' },
  { slug: 'napi-cli', filter: '@napi-rs/cli' },
]

function githubHeaders(): Record<string, string> {
  const headers: Record<string, string> = {
    'User-Agent': 'napi-rs-website',
    Accept: 'application/vnd.github+json',
  }
  if (process.env.GITHUB_TOKEN) {
    headers.Authorization = `token ${process.env.GITHUB_TOKEN}`
  }
  return headers
}

/** Fetch every release page, paginating while a full 100-length array returns. */
async function fetchAllReleases(): Promise<unknown[]> {
  const headers = githubHeaders()
  const all: unknown[] = []
  let page = 1
  let more = true
  while (more) {
    const res = await fetch(`${RELEASES_URL}&page=${page}`, { headers })
    if (!res.ok) {
      throw new Error(
        `GitHub releases request failed (status=${res.status}) on page ${page}`,
      )
    }
    const json: unknown = await res.json()
    if (!Array.isArray(json)) {
      throw new Error(
        `GitHub releases response was not an array (status=${res.status}) on page ${page}`,
      )
    }
    all.push(...json)
    more = json.length === 100
    page++
  }
  return all
}

async function main(): Promise<void> {
  const releases = await fetchAllReleases()
  console.log(`fetched ${releases.length} releases`)

  // One named export per page (e.g. NAPI_HTML), mirroring
  // components/landing/live-demo-code.gen.ts — each page island imports only its
  // own string, so the others never enter that page's module graph.
  const exports: string[] = []
  for (const { slug, filter } of PACKAGES) {
    const md = await buildChangelogMarkdown(releases, filter, 'en')
    const html = await renderChangelogHtml(md)
    const constName = `${slug.toUpperCase().replace(/-/g, '_')}_HTML`
    exports.push(`export const ${constName} = ${JSON.stringify(html)}`)
    console.log(`  ${constName.padEnd(18)} ${html.length} bytes`)
  }

  const banner =
    `// GENERATED by scripts/build-changelog.ts — DO NOT EDIT.\n` +
    `// Full napi-rs release history rendered to HTML per package, baked at build\n` +
    `// so the changelog pages are pure-static (no runtime loader, no per-request\n` +
    `// GitHub fetch, no worker OOM) and served cookie-agnostic like the .md docs.\n` +
    `// Regenerate with: GITHUB_TOKEN=… oxnode scripts/build-changelog.ts\n\n`

  const body = banner + exports.join('\n\n') + '\n'

  writeFileSync(outFile, body, 'utf8')
  console.log(`wrote ${outFile}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
