// @generated by scripts/convert-content.mjs
//
// Head sidecar for an @void/md island page whose byte-0 <script> block hides
// the frontmatter from Void core's title derivation. Regenerated by the
// converter; do not edit by hand. See renderHeadSidecar() for the full why.
import { defineHead } from 'void'

// Opt OUT of auto-prerender so the per-request COOP/COEP isolation
// headers from void.json reach this document — it hosts the in-browser
// @napi-rs/image WASM demo, which needs cross-origin isolation
// (SharedArrayBuffer). A prerendered static page would bypass those
// headers. Mirrors pages/en/index.server.ts (landing).
export const prerender = false

export const head = defineHead(() => ({
  title: 'WebAssembly 与 WASI',
  meta: [
    {
      name: 'description',
      content:
        '在 Node.js 和浏览器中构建、打包、测试并运行 NAPI-RS WASI 回退。',
    },
  ],
}))
