// GENERATED by scripts/build-demo-lqip.mjs — DO NOT EDIT.
// Tiny blurred WebP LQIP for the image playground's result slot (produced from
// nasa-4928x3279.png via @napi-rs/image), replacing the old Next blurDataURL.
// Regenerate with: node scripts/build-demo-lqip.mjs

export const NASA_LQIP =
  'data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBQCdASogABUAPrVSpE2nJCOiKAgA4BaJaQAA7OZwU3R/P/RVAPF9truNGqMfNBzAAP7+hxNoEFhHpjscvEEnpBokOpeXhRZ7ENWmazRM9aOWG1a0q/rR5/ruTFZzbn+vn85YEJajLNPUp9Jgn87hFG3CtOotNSOZdGKFCNb60Mq25j6vFf3sk3TgAA=='
